package com.twitter_backend.twitter_backend.controllers;

import com.twitter_backend.twitter_backend.dto.ReplyDTO;
import com.twitter_backend.twitter_backend.mappers.ReplyMapper;
import com.twitter_backend.twitter_backend.models.Reply;
import com.twitter_backend.twitter_backend.services.ReplyService;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.http.HttpStatus;
import org.springframework.http.ResponseEntity;
import org.springframework.web.bind.annotation.*;

@RestController
@RequestMapping("/replies")
public class ReplyController {

    @Autowired
    private ReplyService replyService;

    @Autowired
    private ReplyMapper replyMapper;

    /**
     * Creates a new reply.
     * Expects JSON data in the request body with the following structure:
     * {
     *   "id": null, // Optional: Automatically generated by the server
     *   "replyId": null, // Optional: Additional identifier for the reply
     *   "tweet": {
     *     "id": 1 // ID of the associated tweet
     *   },
     *   "user": {
     *     "id": 123 // ID of the user who posted the reply
     *   },
     *   "createdAt": "2022-03-28T10:15:30" // Creation timestamp of the reply
     * }
    */
    @PostMapping
    public ResponseEntity<ReplyDTO> createReply(@RequestBody ReplyDTO replyDTO) {
        // Map the DTO to the entity
        Reply reply = replyMapper.toEntity(replyDTO);
        // Create the hashtag using the service
        reply = replyService.createReply(reply);
        // Convert back to DTO for verfication
        ReplyDTO createdReplyDTO = replyMapper.toDTO(reply);
        // Return the created DTO in the response
        return new ResponseEntity<>(createdReplyDTO, HttpStatus.CREATED);
    }
}
